# SPDX-FileCopyrightText: None
# SPDX-License-Identifier: CC0-1.0
Dependencies:
- 'on': ['Linux', 'FreeBSD', 'Windows', 'Android']
  'require':
    'frameworks/extra-cmake-modules': '@stable'

Environment:
  KDECI_BUILD: "TRUE"

Options:
  setup-dbus-session: False
  require-passing-tests-on: [ '@all' ]
  cmake-options: -DBUILD_STANDALONE=OFF
